version: '2'

services:

  web:
    build: './frontend'
    # volumes:
    #   - './frontend:/usr/share/nginx/html/'
    # command: [ "tail", "-f", "/dev/stdout" ]

  app:
    build: './frontend/app'

    command: [ "tail", "-f", "/dev/stdout" ]

  api:
    build: './backend/api'
    volumes:
      - './backend/api:/app:ro'
    working_dir: '/app'
    environment:
      DATASTORE_URI: 'postgres://postgres@datastore'

  datastore:
    build: './backend/datastore'
    volumes:
      - 'subsunday-data:/var/lib/postgresql/data'

volumes:
  subsunday-data: {}
