version: '2'

services:

  web:
    build: './frontend/server'
    volumes:
      - 'shared-build:/usr/share/nginx/html'

  app_builder:
    build: './frontend/app'
    volumes:
      - 'shared-build:/usr/src/app/build'

  api:
    build: './backend/api'
    volumes:
      - './backend/api:/app:ro'
    working_dir: '/app'
    environment:
      DATASTORE_URI: 'postgres://postgres@datastore'

  datastore:
    build: './backend/datastore'
    volumes:
      - 'subsunday-data:/var/lib/postgresql/data'

volumes:
  subsunday-data: {}
  shared-build:
    driver: local
