version: '2'

services:

  app_builder:
    ports:
      - '3000:3000'
    volumes:
      - './frontend/app:/usr/src/app'
    command: [ "tail", "-f", "/dev/stdout" ]

  web:
    ports:
      - '8080:80'

  api:
    environment:
      DEBUG: 'yes'
